### ISSUE TITLE
unable to run tests in Node 8

### ISSUE THREAD

**Issue by oprogramador** [crookedneighbor/csv-stringify-as-promised#1]
NodeJS: 8.6.0
npm: 5.2.0
OS: Linux Mint 17 Qiana (Linux kernel 3.13.0-24)

When I'm trying to run the tests in Node 8 with `./node_modules/.bin/mocha`, I obtain `TypeError: Module._cache.hasOwnProperty is not a function`

**Comment by oprogramador** [comment]
I resolved it and generally modernized this library in https://github.com/crookedneighbor/csv-stringify-as-promised/pull/2/files

**Comment by crookedneighbor** [comment]
The only actual problem was that the stubbing dependency `testdouble` had incompatibilities with Node 8. After updating the dev dependencies, the tests run just fine.
